# Development Dockerfile

FROM golang:1.20

WORKDIR /app

# Install Air for live reloading
RUN go install github.com/cosmtrek/air@latest

# Install Templ
RUN go install github.com/a-h/templ/cmd/templ@latest

# Install npm for tailwindcss and esbuild
RUN apt-get update && apt-get install -y npm
RUN npm install -g npx esbuild

# Copy go mod and sum files
COPY go.mod go.sum ./
RUN go mod download

# Copy the rest of the files
COPY . .

# Install npm dependencies
RUN npm install

# Expose the port
EXPOSE 4000

# Command to start the development environment
CMD ["air"]
